spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: rest-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_udemy?userTimezone=true&serverTimezone=UTC
    version: 8.1
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
      properties:
        hibernate:
      show-sql: false
logging:
  level:
    #root: WARN
    br.com.fms: DEBUG